### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'data' in null

### ISSUE THREAD

**Issue by anis-moubarik** [wycats/handlebars.js#1003]
I got the following error.
`TypeError: Cannot use 'in' operator to search for 'data' in null
    at Object.compile (/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:467:19)
    at HandlebarsEnvironment.hb.compile (/node_modules/handlebars/dist/cjs/handlebars.js:34:41)
    at ExpressHandlebars._compileTemplate (/lib/express-handlebars.js:239:28)
    at ExpressHandlebars.<anonymous> (/lib/express-handlebars.js:124:25)
    at /promise/lib/core.js:33:15
    at flush (//node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:419:13)`

After a bit of searching I found out that the file in the dist folder (compiler.js) missed the `options = options || {}` thus giving the null error. Adding that line solves the error. (The same code worked with 3.0.1 and stopped working with 3.0.2).

Further inspection shows handlebars/lib/handlebars/compiler/compiler.js:448 the compile functions parameter options = {}, is the problem. I'm using express and express-handlebars, and they don't support es6? Not sure.

**Comment by kpdecker** [comment]
express-handlebars is defaulting the handlebars configuration to null vs. undefined. The reason that the prior code worked was that it was attempting to save a few bytes vs. the more correct parameter handling the the new es6 code compiles to.
https://github.com/ericf/express-handlebars/blob/d5e664b99c75747a5251343b5a98f8da32ca0ae5/lib/express-handlebars.js#L31

I'm not certain the best path here as it feels like passing null for defaults if fundamentally wrong and the behavior seen previously was an artifact of the implementation vs. an intentional API. While sorting out wether this is something that handlebars or express-handlebars should fix, I'd recommend passing in `compilerOptions: undefined` to express-handlebars. That appears like it will fix the issue in the near term without having to pin any libraries.

/cc @ericf

**Comment by sahat** [comment]
@kpdecker +1 for `compilerOptions: undefined` as a temporary workaround.

**Comment by anis-moubarik** [comment]
@kpdecker thanks, that's a good workaround.

**Comment by ee99ee** [comment]
+1 for the workaround... but this is only a temporary. I'll look into a fix for this as well.

**Comment by ericf** [comment]
@kpdecker so what have you decided on this issue? Are you planning to make a change to Handlebars to add back the falsy check that was removed in the ES6 conversion?

Given that the ES6 conversion was released as a patch release it seems that your intention was purely for authoring style and cosmetics and not to semantically change the APIs. So my vote would be to add back the falsy check that was removed. If you don't plan to go that route, then close this as wontfix, and I'll update Express Handlebars to deal with the API change.

**Comment by kpdecker** [comment]
Closing this as while it's a bit unfortunate that it caused issues, I can argue that it's semantically equivalent in my mind, simply following the languages newly codified spec for what defined is, and rolling a major update for a small change seems like unnecessary overhead for the ecosystem as a whole.

**Comment by ericf** [comment]
It clearly wouldn't be a major update. This could have been a simple: unpublish of 3.0.2, add back the removed falsy check, and publish 3.0.3. Maybe if more issues arise with this refactor you'll be up for reconsidering…

**Comment by kpdecker** [comment]
He issue is we can not move forward with es6 defaults if we handle null.
I'm leaving the behavior as is. Please use undefined for your defaults or
better yet, omit the field.

**Comment by ericf** [comment]
> He issue is we can not move forward with es6 defaults if we handle null.

This is not true, these are not mutually exclusive. The function can still do type checking for `null`.

**Comment by kpdecker** [comment]
Official stance is that null is not supported.
