### ISSUE TITLE
Strict mode shouldn't be enforced in conditionals

### ISSUE THREAD

**Issue by nevir** [wycats/handlebars.js#1063]
Currently:

```js
let template = Handlebars.compile('{{#if foo}}{{foo}}{{/if}}', {strict: true});
template({}); // Throws `Error: "foo" not defined in [object Object]`
```

I definitely expected this to not be the case (you should be able to explicitly protect against missing values, IMO)!

**Comment by kpdecker** [comment]
There is nothing special about `if` or any other helper by design. Things become very complicated if we allow decide that some subset of helpers are treated differently than others.

We could potentially not throw for missing variables for any helper variable reference, instead leaving those checks to the helper, but I'm hesitant to make such a change without hearing from users of this feature. @nzakas you requested this initially, any opinions?

**Comment by nzakas** [comment]
Is it the `if` throwing the error here? If so, I agree that's undesirable. We need some way to guard against missing data (similar to using `if` in JavaScript to determine if a property exists before using it).

**Comment by kpdecker** [comment]
Right now the throw is done on the reference to the variable, similar to Javascript  behavior when referencing an undeclared global without doing a `typeof` check. Just like under javascript, the `if` operation does not run in this case. The generated code right now is something like this:

```
helpers.if(strict(context, 'foo'))
```
Where strict is [this method](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/runtime.js#L71).

The proposed change would be for strict checking to occur for all of these references to foo, but nothing else: 
- `{{foo}}` : `strict(context, 'foo')`
- `{{foo.foo}}` : `strict(strict(context, 'foo'), 'foo')`

But these `foo` references would not be checked by the generated code
- `{{bar foo bar=foo}}` : `helpers.bar(context.foo, {bar: context.foo})`

The helper would not be able to differentiate between explicitly undefined and missing as they would just have the `undefined` value and not the name to do a `in` check.
