### ISSUE TITLE
Mongoose method rendering

### ISSUE THREAD

**Issue by latitudehopper** [wycats/handlebars.js#1073]
How do you render a mongoose model method? If I try {{ model.gravatar }} it works but I cannot pass values through by going {{ model.gravatar({size: 300}) }} for example. Is there a way to do this?

**Comment by kpdecker** [comment]
I'm not sure what you are referring to by mongoose, but there is no way to pass arbitrary arguments to functions executed from a template as they are treated as helpers. It will always pass the options object for example.

If your methods are safe with this, then you could write a subexpression helper that generates your hash values so you could in theory do something like this:

```
{{ model.gravatar (object size=300) }}
```

```
Handlebars.registerHelper('object', function(options) {
  return options.hash;
});
```

There are many other ways that this can be done as well, but generally I'd recommend pre-calculating these values in your code that calls the template rather than trying to shoehorn dynamic calls from the template. It can be made to work but it might not be the most efficient or stable.
