### ISSUE TITLE
handlebars 3.0.x fails to load when mail chimp embed script included

### ISSUE THREAD

**Issue by rounders** [wycats/handlebars.js#1075]
I've noticed that If I use MailChimp's embedded popup signup form, Handlebars doesn't successfully load. 

Example JSBIN:
https://jsbin.com/kuwetidisu/1/edit?html,console,output
when the jsbin is run, the console output complains with "ReferenceError: Can't find variable: Handlebars"

Here's the same jsbin but without the mailchimp embed script:
https://jsbin.com/nelemarova/1/edit?html,console,output
in this jsbin Handlebars loads just fine.

Anyone have any thoughts on what could cause this? Should I be reporting this to mailchimp instead?

**Comment by kpdecker** [comment]
Mail chimp is creating an AMD loader that Handlebars then registers against. This is poor form for an embedded library as this can break any code following the UMD pattern.

I'd raise the issue with them to see if there is any way that they can use a private AMD loader (I am not sure if that is possible) otherwise you'll need to either load Handlebars prior to their scripts or write a shim to map the AMD Handlebars instance to the global space. This isn't something that we can really do in the handlebars library without breaking existing users :/

**Comment by rounders** [comment]
@kpdecker thanks, I appreciate the explanation :+1: , I will contact mailchimp
