### ISSUE TITLE
Consider including browser flag in package.json

### ISSUE THREAD

**Issue by kpdecker** [wycats/handlebars.js#1102]
Want to set the `browser` field to either the dist/handlebars file or lib/handlebars to avoid issues with require.extension code being included on the client.

Should look at using `browser` as an object rather than a string:
https://github.com/defunctzombie/node-uuid/blob/master/package.json#L30

This might let us handle the runtime and the full library.

**Comment by ouijan** [comment]
This would be incredibly useful for circumstances where we don't have access to a `webpack.config`. 

For example, `import * as Handlebars from 'handlebars';` within an angular project causes the `fs` not found issue because it is importing the wrong build. It should be pointing to `dist/handlebars.min.js`. 

Using `import * as Handlebars from 'handlebars/dist/handlebars';` causes typedef errors.

**Comment by nknapp** [comment]
I'm open for trying this. Could you open a PR to the 4.x branch?

The difficult part is determining whether this has any breaking side-effects for other users. Any ideas?

**Comment by ouijan** [comment]
I've opened a PR to add browser to the `package.json`. It's hard to write a test for this kind of change I know it resolves issues in my use case but welcome ideas on how to more reliably test it.
