### ISSUE TITLE
should whitespace control strip "special" whitespace?

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1104]
such as non-breaking whitespace.

```js
// {{path~}}&nbsp; asdf {{~path}}
require("handlebars").compile("{{path~}}  asdf {{~path}}")({path:"asdf"});
//-> asdfasdfasdf
```
Should it not produce `asdf  asdfasdf` ?

**Comment by kpdecker** [comment]
Sorry you're running into issues here. I fear that whatever we do here, someone is going to end up confused since these appear to be whitespace to the naked eye so I don't think changing the behavior will help anyone out. I'd recommend using entity references or not utilizing whitespace control if you have significant whitespace that you are rendering.

**Comment by stevenvachon** [comment]
Not actually running into issues. I'm writing a lib that uses the Handlebars AST and was curious about the best way to handle such a case.

**Comment by stevenvachon** [comment]
Thanks for your answer!

**Comment by kpdecker** [comment]
Ah, if going for compatibility, we use the javascript definition of whitespace. ` [ \f\n\r\t\v​\u00a0\u1680​\u180e\u2000​-\u200a​\u2028\u2029\u202f\u205f​\u3000\ufeff]`

**Comment by stevenvachon** [comment]
Cool, thanks.

**Comment by kpdecker** [comment]
Forgot to mention, if you are working in javascript, then the whitespace control logic is actually a standalone AST visitor:
https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/whitespace-control.js

Could save you some of the headaches of trying to rewrite it and also help avoid duplication.
