### ISSUE TITLE
#each does not work in a table in html5 <template> tag

### ISSUE THREAD

**Issue by Jb300** [wycats/handlebars.js#1133]
Using the html5 <template> tag causes problems when trying to use #each in a table environment. [object Object] is displayed instead of the values of an array.

See http://stackoverflow.com/questions/33761852/handlebars-js-and-html-table-displays-object-object-instead-of-values/33778701#33778701

Or the jsfiddle: https://jsfiddle.net/ouhd7sLg/2/

**Comment by kpdecker** [comment]
The problem is that you are trying to use the html to generate the template but mustache statements can generate invalid html which the browser tries to correct for.

If you look at the html that is passed to handlebars, you get this:

```        
					{{#each weekdays}}
					
					{{/each}}
				<table>
			<thead>
				<tr>
					<!-- displays [object Object] with <template> tag --><th>{{this}}</th></tr>        
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>2</td>
				</tr>
			</tbody>
		</table>
	```

The contents of a `script` tag are not parsed in the same manner so you don't have a corrupted template.

In generally I'd recommend that you use precompiled templates rather than inlining them into your html, but if you do inline them in your html, you need to use the `script` tag.
