### ISSUE TITLE
Stream support?

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1150]
Would be nice if it could parse chunks.

**Comment by kpdecker** [comment]
It's not exactly clear what this would entail or what the benefit would be. What is your use case?

**Comment by stevenvachon** [comment]
Faster parsing via file/http stream input. A use case could be build scripts.

**Comment by kpdecker** [comment]
Reading the template is not the slow part of the compilation pipeline, it's the actual parsing and if you're putting in template that are large enough that you have concerns about the IO wait time or the cost of loading the template into memory prior to parsing, I'd start to wonder if there is too much data hard coded in the template.

That and our [parser generator](http://zaach.github.io/jison/docs/#using-the-generated-parser) does not support a stream mode so the cost/benefit here doesn't really work out in my head.

**Comment by stevenvachon** [comment]
With a stream, many templates could be parsed concurrently with less memory consumption and garbage collection.

**Comment by kpdecker** [comment]
It's a micro-optimization at best, if you are pushing megabytes of
templates into the parser, your going to see more issues from being CPU
bound in the parser itself.

If someone from the community were to investigate, we might consider
accepting it, but I fear that would basically be a full rewrite of the
parser.

**Comment by jakearchibald** [comment]
With streaming coming to the client & service worker, this may be worth revisiting?https://jakearchibald.com/2016/streams-ftw/#creating-one-stream-from-multiple-sources-to-supercharge-page-render-times

Also, dustjs was of real benefit when I built https://wiki-offline.jakearchibald.com/ (explaination https://www.youtube.com/watch?v=d5_6yHixpsQ&feature=youtu.be&t=4m22s), since some of my data was slower to arrive and I wanted a fast first render.

Dustjs handles promises & streams as template values, but unfortunately I have nothing nice to say about dustjs's syntax.

**Comment by mathiasbynens** [comment]
One more resource to add to the list: https://jakearchibald.com/2016/streaming-template-literals/ (it links to this issue)
