### ISSUE TITLE
old IE difference in context

### ISSUE THREAD

**Issue by smhg** [wycats/handlebars.js#1160]
If you run this [JS Bin](https://jsbin.com/kazifonehu/1/edit?html,js,output) in IE9, the result is different compared to Chrome or FireFox. There is no difference using Handlebars 3.

Am I wrong assuming the result should be the same? Is old IE still supported?

**Comment by kpdecker** [comment]
This is likely happening due to use strict that was added to the library as part of the build process. Since strict mode is the path of the future, we should look at adding a `context` parameter to the helpers options hash as this won't be impacted by non-strict call context changes.

**Comment by kpdecker** [comment]
@jonschlinkert @ErisDS @wycats @mmun This can be done without a breaking change by adding a field to options and nothing else, but I worry that is leaving many helpers broken for uncommon but difficult to debug use cases. Part of me wants to make this breaking and change helpers to avoid context as this is faster and has a likely cleaner API. Since this would be a breaking change for the helpers API 
as it is, this would give the opportunity to clean up the painful `helper(...args, options)` API.

So the current helper calls would go form something that looks vaguely like:

```
helper.call(depth0 != null ? depth0 : {}, 1, 2, 3, {
  fn: () => {},
  inverse: () => {}
});
```

To:
```
helper({
  fn: () => {},
  inverse: () => {},
  context: depth0,
  args: [1, 2, 3],
});
```

(@wycats, I seem to remember you having issue with the name `fn` but I don't remember how that conversation went)

Technically this feels like a much better solution, my only concern is how much pain this will be for the community as well as how well this matches with with the input API for htmlbars as I believe they choose a different route there. There will be some level of pain for sure so the question is if this passes the pain v. value threshold.

**Comment by kpdecker** [comment]
Actually, I should have looked at this further before making assumptions, this is an artifact of the changes to depth handling introduced in 4 (https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v400---september-1st-2015) as well as a bug that has been fixed in master.

http://jsbin.com/musiyalufi/1/edit?html,js,console,output demonstrates the proper behavior across all browsers.

Regarding the helper changes proposed above, avoiding the breaking change now since my assumption about what the error case was was incorrect.
