### ISSUE TITLE
block params as number?

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1199]
```handlebars
{{#path 1 2 3 as |4|}} text {{4}} {{/path}}
```
Should we not throw an error if the first char in the variable name is not a letter?:
```handlebars
{{#path 1 2 3 as |a4|}} text {{a4}} {{/path}}
```

**Comment by kpdecker** [comment]
There has never been a requirement that we follow javascript id patterns, so `{{4}}` is just fine in the language. What is the argument for changing this?

**Comment by stevenvachon** [comment]
It conflicts with `{{4}}` which is already supported by handlebars as a number literal.

**Comment by kpdecker** [comment]
I don't believe this to be the case from my test compilation, it resolves
the value (or helper) "4". Can you put together a fiddle showing the
opposite if you are seeing different behavior?

**Comment by stevenvachon** [comment]
It conflicts semantically and doesn't work; no actual error. Because of this, it should probably throw when being parsed.

```js
console.log( require("handlebars").compile("{{#each list  as |value 4|}} {{value}} {{4}} {{/each}}")({list:[0]}) )
```
produces `0 0`. `{{4}}` doesn't work as might be expected.

An example of something similar that does throw a parse error:
```handlebars
{{#each list  as ||}} {{/each}}
```

**Comment by kpdecker** [comment]
This is operating as expected, {{4}} is resolving the second block parameter. Without the block parameter it would resolve to context['4'] so both behaviors are consistent. There is some level of oddity as numbers are treated as literals in any other position, but I'm not willing to break a use case that has been around for this long because someone chooses a bad variable name.
