### ISSUE TITLE
{{{ is adding an extra <p> at the end

### ISSUE THREAD

**Issue by hguillermo** [wycats/handlebars.js#1238]
I have this markup:
```
<p>While many people want to "buy local," the convenience of one-click shopping from services like Amazon and Instacart can trump goodwill. The founders of Kiezkaufhaus want to make online shopping from one's neighborhood as easy as buying from a big-box website. The site connects small local businesses on a single online platform and offers on-demand delivery service that uses eco-friendly bikes powered by senior citizens.<p>
```

After doing this {{{myVarHer}}} it creates another empty ```<p>`` `at the end. Not sure why.

**Comment by stevenvachon** [comment]
Use \`\`\`
https://guides.github.com/features/mastering-markdown/

**Comment by hguillermo** [comment]
The value is coming from the db as a HTML and it is passed to the context. That's why I am using {{{. I am not sure if I understood what you are saying.

**Comment by stevenvachon** [comment]
We cannot see your html because you are not using markdown correctly to display your code.

**Comment by hguillermo** [comment]
```
<p>While many people want to "buy local," the convenience of one-click shopping from services like Amazon and Instacart can trump goodwill. The founders of Kiezkaufhaus want to make online shopping from one's neighborhood as easy as buying from a big-box website. The site connects small local businesses on a single online platform and offers on-demand delivery service that uses eco-friendly bikes powered by senior citizens.</p>
```

**Comment by stevenvachon** [comment]
And the html around your variable?

**Comment by nknapp** [comment]
@hguillermo The closing tag of your code is  `<p>` and not `</p>` (no slash). Is it the same in the real code our did this happen when you wrote the comment.

When you write `<p>text<p>` instead of `<p>text</p>`, your browser will clean the code by closing the first `<p>` tag and starting another one afterwards. If you are looking at the result in the DOM-Inspector, it will look like `<p>text</p><p></p>`. When you inspect the network traffic of the page-source, it should look normal.

**Comment by hguillermo** [comment]
OMG! such a terrible mistake by my part. I just didn't see it the incorrect markup. I guess one of our  markup validator library is not right. 
My apologies guys for wasting your time and thanks a lot.
