### ISSUE TITLE
Error with @partial-block returning calling parent partial

### ISSUE THREAD

**Issue by alekbarszczewski** [wycats/handlebars.js#1276]
```hbs
// inline partial simply returning @partial-block
{{#*inline "myPartial"}}
  {{> @partial-block }}
{{/inline}}

// render partial
{{#> myPartial}}
  {{> myPartial}} // <-- @partial block should be empty for this invocation, but it is not...
{{/myPartial}}
```

When executing this template I get `RangeError: Maximum call stack size exceeded`.
It seems that recursive invocation of partial receives @partial-block from parent invocation of same partial. When passing @partial-block explicitly no error is thrown:

```hbs
// inline partial simply returning @partial-block
{{#*inline "myPartial"}}
  {{> @partial-block }}
{{/inline}}

// render partial
{{#> myPartial}}
 {{#> myPartial}}{{/myPartial}} // <-- empty partial block works
{{/myPartial}}
```

**Comment by andreasryland** [comment]
I'm having a problem with he same issue. I want a partial to have an optional partial-block which works out ok. But if it is nested inside a different partial and called without a partial block then it gets the parent block.

Imo 
`{{#> myPartial}}{{/myPartial}}`
and
`{{> myPartial}}`

Should be the same, as neither are receiving any partial block content.

And if this is intended to be like that then at least it should be possible, perhaps with a custom handlebars helper, inside the partial to know if the @partial-block it had was its own or one that was passed down from a parent. Then the partial could choose to ignore any blocks that were not passed directly to it.

**Comment by rafde** [comment]
Which version of Handlebars are you seeing this issue in? 4.0.6?

**Comment by lawnsea** [comment]
@alekbarszczewski I have good news and bad news. The good news is that 4.0.6 fixes the bug you ran into. The bad news is that now your code results in a different error: `Error: The partial @partial-block could not be found`. This is because, as currently implemented, the block argument to a partial block template is not optional.

Unfortunately, the design of partial blocks (starting in #1018) was split across several issues and the final implementation was under-specified. That said, I don't see any indication that the syntax you employ was intended to be supported.

**Comment by andreasryland** [comment]
I think the issue here is that a partial that is not called as a block partial can get a partial block if it is nested inside a different partial.

I believe {{> myPartial}} should always have an empty @partial-block, if it gets its parents block then that block will contain itself which seems an odd behaviour.

See examples below

// inline partial simply returning @partial-block
{{#*inline "myPartial"}}
  <p>something</p>

  {{#if @partial-block}}
    {{> @partial-block }}
  {{else}}
    <p>something else</p>
  {{/if}}
{{/inline}}


// render partial
// works:
{{#> myPartial}}
  <p>something entirely different</p>
{{/myPartial}}

// works
{{> myPartial}}

// does not give intended output
{{#> myOuterPartial}}
  <h2>Hello</h2>
  {{> myPartial}}
{{/myOuterPartial}}

// works
{{#> myOuterPartial}}
  <h2>Hello</h2>
  {{#> myPartial}}
    <p>world</p>
  {{/myPartial}}
{{/myOuterPartial}}

// works
{{#> myOuterPartial}}
  <h2>Hello</h2>
  {{#> myPartial}}{{/myPartial}}
{{/myOuterPartial}}

**Comment by alekbarszczewski** [comment]
@lawnsea Thanks for the answer. Indeed 4.0.6 fixes this issue as you said.

I did not know that it is possible to check for @partial-block existance using `{{#if @partial-block}}` (thanks @andreasryland !). For me it solves the issue.

**Comment by lawnsea** [comment]
Ok, thanks for confirming, @alekbarszczewski.

@andreasryland please file a separate issue. I agree that the current behavior is underspecified and odd.
