### ISSUE TITLE
Version 4.0.6 not available in bower and on AWS (aka Runtime version state 4.0.6 in the comment but 4.0.5 in the actual version?)

### ISSUE THREAD

**Issue by blaasvaer** [wycats/handlebars.js#1286]
Only adds to the confusion when trying to get the right runtime version. Which I've spent the major part of the day trying to figure out.

**Comment by nknapp** [comment]
@lawnsea I've noticed that on http://handlebarsjs.com/installation.html the current version is still 4.0.5
Just updating the link and the label would not be enough since, http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v4.0.6.js does not work. 

Something seems to be missing in the last release.

**Comment by nknapp** [comment]
The current master-branch still has 4.0.5 in its package.json, because the version-number will only be bumped on the next release. Then it will probably be 5.0.0, since there is a 4.x-branch now.

This means that [the last passing build](http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-latest.js) is also 4.0.5. We could bump the master-branch to 5.0.0-alpha, but I don't know if that would describe the state of the master-branch correctly.

@lawnsea @wycats Can anyone publish version 4.0.6 to bower and aws?

**Comment by lawnsea** [comment]
Updating the version on the website will require landing a PR in https://github.com/wycats/handlebars-site.

I don't have the commands I ran to do the release in my bash history anymore, unfortunately. It's entirely possible I borked the bower and AWS part.

**Comment by nknapp** [comment]
I wouldn't have thought about bower and AWS (I only use npm). Would be great of there was a page with the checklist and the commands for performing a release, so that nothing gets forgotten.

**Comment by lawnsea** [comment]
There is: https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md#releasing. IIRC, I had some trouble with the generator because I had already bumped the version.

Looking back at my DM history with @wycats, I didn't get AWS creds or ask about bower. We're going to need some help to finish this off.

**Comment by nknapp** [comment]
I released 4.0.6 to bower now. Can anybody check if it worked? I don't use bower.
AWS and handlebars.com is still missing 

The bower release is in the https://github.com/components/handlebars.js repository.

**Comment by nknapp** [comment]
This should all work now. Closing.

**Comment by nknapp** [comment]
Please comment on #1312 if you need 4.0.6 or 4.0.7 on AWS.
