### ISSUE TITLE
UMD vs AMD builds

### ISSUE THREAD

**Issue by robbie0630** [wycats/handlebars.js#1328]
I write applications using RequireJS because it helps modularize and organize my code. Handlebars.js provides both AMD and UMD builds. I understand that these are both AMD-compatible builds. My question is what build is recommended for normal use? Will AMD builds ever be deprecated in favor of UMD builds? Or should I stick with AMD builds?

**Comment by nknapp** [comment]
It seems to be that there is nobody who can give advice on this and has the time to do so.
 
All I can say is that I would not remove any build without a very good reason, because 

* that would probably break many projects and that's in nobody's interest. 
* the builds are generated automatically, so there is no manual overhead in creating them. There is no reason to remove anything.

I feel a little sad, because I would have liked to answer your question earlier and I could have come up with this answer when you asked it. But I am relatively new to the project and it felt arrogating to make such a decision, so I had hoped someone else would answer.

Still, I think my oppinion on (not) removing builds is shared by the other collaborators.

**Comment by TrySound** [comment]
@nknapp Well the problem is fragmenting when one thing can be used in different equal ways. This generates such questions. Breaking change is not a problem if you do not afraid major releases. Nobody will be broken, but there will be one universal not confusing entry point.
