### ISSUE TITLE
Is there any way can use #if function logicValue in handlebars like in Meteor Spacebars

### ISSUE THREAD

**Issue by kothari775** [wycats/handlebars.js#1348]
I am trying to move Meteor project into Express. Currently using [hbs](https://www.npmjs.com/package/hbs)  package with express which internally dependes on this handlebars. How can I get all {{#if}} behavior Meteor Spacebar here in handlebars.

Example in Meteor I used to use #if with multiple way

- {{#if dataExists}} - Boolean
- {{#if obj.key}} - Object.prop
- {{#if function}} - helper function returns true/false
- {{#if function comparedWithFunctionReturnedValue}} - helper function contains one argument, do some logic inside it and returns it.

**Comment by nknapp** [comment]
If you don't want to change anything in your templates, you have to override the if-helper.
Something like:

```
Handlebars.registerHelper('if', function(arg1, arg2, options) {
  // If there is only one argument, the options will be in the wrong argument
  if (options === undefined && typeof arg2 === 'object') {
    options = arg2 
    arg2 = undefined
  }
  if (/*your checks here */) {
    return options.fn(this)
  } else {
    return options.inverse(this)
  }
})
```
The original implementation of the if helper is [here](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/helpers/if.js)

I think the helper could be written in a backward compatible way, so that you won't run into problems with other helpers.

You can also register a different helper and change all the calls in your templates.

**Comment by kothari775** [comment]
Thanks @nknapp. I already gone through shared if.js earlier, but I think as you said I need to re-write to support current Meteor style. 

> if ((!options.hash.includeZero && !conditional) || isEmpty(conditional)) {
      return options.inverse(this);
    } else {
where I need to remove it and check with my work around for Meteor style. Once again Thanks !!

**Comment by nknapp** [comment]
Glad to help
