### ISSUE TITLE
compiler-api.md shows an example which does not work when the with-helper is used.

### ISSUE THREAD

**Issue by bdiz** [wycats/handlebars.js#1376]
This issue is following conversation with @nknapp here: https://github.com/wycats/handlebars.js/commit/c9970200a04a8629b5e9b1ed3c540d391ab00f26#commitcomment-23827796

Issue is regarding the example in the compiler-api.md doc here: https://github.com/wycats/handlebars.js/blob/c9970200a04a8629b5e9b1ed3c540d391ab00f26/docs/compiler-api.md#L307

When using the with helper, the lookupLowerCase helper no longer gets called. I think the with helper is being executed with the original Handlebars, not the MyCompiler. 

Here is a jsfiddle to demonstrate: https://jsfiddle.net/ujp6v98h/

I tried getting it to use MyCompiler when comping the content in the with-helper without success (got an infinite loop with my implementation).

**Comment by nknapp** [comment]
I think what is missing in there is the line

```js
MyCompiler.prototype.compiler = MyCompiler;
```

which makes sure that the overridden compiler is also used for compiling the content of BlockStatements (see https://jsfiddle.net/ujp6v98h/1/)

The example is still not working, but this time the reason is that `helpers.lookupLowerCase` will look for `insidewith` rather than `insideWith` (it's called "lookupLowerCase" not "lookupIgnoreCase").

**Comment by bdiz** [comment]
Yep, the missing line is what it was. Thank you very much @nknapp!
