### ISSUE TITLE
Handlebars with Koa

### ISSUE THREAD

**Issue by Extarys** [wycats/handlebars.js#1378]
Heyhey!

I would like to use the native handlebar library because most libs failed to implement some features I need.

I'm using Nodejs with Koa.

I tried koa-views but it lacks layout.
I also tried koa-hbs/koa-handlebars but they use deprecated functions.

I would prefer to use handlebars and handlebars-layout libraries as I will always get the latest version. Also because I think it would be easier if I want to implement client-side rendering for some things.

Any thoughts? How can I do this?

Thanks!

**Comment by nknapp** [comment]
I would not recommend Handlebars for client-side rendering. Mostly, because there is no support for incremental updates of the DOM. Handlebars does not use a virtual DOM, it only uses strings. There is the "incremental-bars"-project which I have not used myself, but it promises to handle this. 

Server-side rendering and static-page generators, sure, use Handlebars. 
I don't know too much about `koa-views` or `koa-hbs`. But you can use  [partial-blocks](http://handlebarsjs.com/partials.html) to build layout partials, so I would try `koa-views`.
