### ISSUE TITLE
Simplify registerPartial and compile invocation

### ISSUE THREAD

**Issue by wlycdgr** [wycats/handlebars.js#1449]
Since templates are consistently retrieved by id, mightn't it be nice to move those imperative bits inside and clean invocation to:

Handlebars.registerPartial('partialName', '#partialTemplateId');
Handlebars.compile('#mainTemplateId');

where the starting # signals to treat the rest of the string as a template id rather than a literal. Or are there enough string literals that start with # out in the wild that this would break backwards compatibility?

**Comment by nknapp** [comment]
I think there are some points against it:

1) In production, you should precompile your templates anyway. Loading the template from a script-element nice to demonstrate handlebars or to put together a quick demonstration, but no more.
2) Handlebars not only works in the browser, but also in NodeJS and appearently also in Java-Nashorn. There is no browser-specific code in there, but loading the template from a DOM-element would be very browser specific. 

Actually, if I would start new webapp project now, I would not use Handlebars to render HTML in the browser. I would use Vue.js, but if you like the Handlebars-Syntax, you could have a look at [Ember](https://www.emberjs.com/) or [Ractive](https://ractive.js.org/). [This video](https://youtu.be/o12-90Dm-Qs?t=48m1s) demonstrates the reason for that: They both (and React and Angular as well) use virtual-dom and incremental updates instead of rendering the whole template over and over again.

I would only use Handlebars on the server and in command-line tools (like static-page- or [readme-generators](https://github.com/nknapp/thought)).
