### ISSUE TITLE
Nested each and this not working as expected

### ISSUE THREAD

**Issue by Shiiboun** [wycats/handlebars.js#1452]
Hi everyone,

I'm trying to get a nested #each loop working but it is not working as expected.
Here's my fiddle https://jsfiddle.net/9D88g/492/

I want something like this: 
module: module1 nodes: node1, node2, node3
module: module2 nodes: node1, node2, node3
module: module3 nodes: node1, node2, node3

I tried to get this working with some variations of {{@../../key}} and block parameters but handlebars wont generate any output after nodes. 
The JSON cant be changed for some reasons.

Thank you.

**Comment by doowb** [comment]
`{{services.nodes}}` is at the root, so you'll need to use the `../../`syntax inside the `{{#each}}` blocks. You can also use `{{@root.services.nodes}}` from any level.

**Comment by Shiiboun** [comment]
Hi doowb. Thanks for your answer.
Can you please explain
> is at the root, so you'll need to use the ../../syntax inside the {{#each}} blocks.

?

**Comment by doowb** [comment]
I updated the jsfiddle to use `../../services.nodes`: https://jsfiddle.net/az9yfnkj/6/

In handlebars, when you enter a block helper like `{{#each}}`, if the data (context) inside the block is different than what the previous data is, then it creates a new "depth". Since `services` is data at depth 0, and by the time you try to use `services`, the depth is 2 (inside 2 `{{#each}}` blocks, you need to "go back" 2 depths by using `../../`. Also, data that is passed in to the compiled function when rendering the template is put onto a special variable called `@root`, so you can use `@root.services` instead of trying to guess how deep you are in the context.

**Comment by Shiiboun** [comment]
Wow I didn't knew that trick! You helped me alot, thank you very much!
