### ISSUE TITLE
How to output a raw partial (not a block)?

### ISSUE THREAD

**Issue by landwire** [wycats/handlebars.js#1479]
Hi there,
sorry I could not use the jsfiddle template as I work with assemble.io and handlebars.js.

I would like to output the raw partial (not compiled) for instance with a helper. Is this possible?
Like so:

Instead of trying to use raw (or markdown) like this:

```
{{{{raw}}}}
<span>{{foo}}</span>
{{{{/raw}}}}
```
I would like to output the contents of a partial (foo.hbs) in raw format:

```
{{{{raw}}}}
{{>foo}}
{{{{/raw}}}}
```
I tried this with markdown:

```
{{{{markdown}}}}
{{>foo}}
{{{{/markdown}}}}
```

and it outputs this: `{{>foo}}`
But I would like this: `<h1>This is the {{title}}</h1>`

content of foo.hbs:
`<h1>This is the {{title}}</h1>`

Anybody could give me a hint on how to achieve this?
The gist here: https://gist.github.com/phobia/9110443 sometimes just returns functions as @doowb already stated, so it is no help to me.

Link to a fairly related github issue:
https://github.com/assemble/assemble.io/issues/73
Also related issues showed this, but this does not help either as far as I can see:
https://github.com/wycats/handlebars.js/issues/1385

Thanks for any help!

**Comment by thenickot2** [comment]
I had to deal with a similar issue and this might give you a different solution. I had a partial that I needed to output it's raw markdown for, for use in clientside rendering (and the partial needed to be defined inline due to how it was generated and saved). After reviewing the handlebars source, it appears that once a partial has been compiled, it cannot be "uncompiled". You can instead look to save that content (additional datastructure, output as a script for clientside rendering, etc) when defining the partial. For example, if you were defining the partial inline like I was:

```
{{{{partial "myPartial"}}}}
  <div>{{myVariable}}</div>
{{{{/partial}}}}
```

```
Handlbars.registerHelper('partial', function(name, options) {
    // Register a partial and output the content in a script for clientside rendering
    Handlebars.registerPartial(name, Handlebars.compile(options.fn()));
    const script = `<script type="text/x-handlebars-template" class="${name}">${options.fn()}</script>`;
    return script;
},
```

Now I have both registered a partial and used the raw representation as needed. While not a direct answer to your question, I hope this helps you. Seems like an interesting thing you're trying to accomplish!

**Comment by dangarfield** [comment]
I had the exact same issue but I was using `gulp-hb`, so I simply created a helper that read and outputted the file. Eg: created a helper file:
```
const partial = (partialName, scriptId) => {
  const partialContent = fs.readFileSync(path.join('path-to', 'templates', partialName + '.hbs'))
  return `<script type="text/x-handlebars-template" id="${scriptId}">\n${partialContent}\n</script>`
}
module.exports = {partial}
```
Ensured that this helper was registered with my gulp config and set up a based watched task.
Now in my main `.hbs` file I simply passed the reference to the partial and an id for the dynamic script:
```
<div class="parent-div">
{{{{partial "profile/profile-card-photos" "profile-card-photos-template"}}}}{{{{/partial}}}}
</div>
```

Which renders:
```
<div class="parent-div">
<script type="text/x-handlebars-template" id="profile-card-photos-template">
<div class="child-div">
<h3>{{someVar}}</h3>
</div>
</script>
</div>
```

This is all that I wanted.
In terms of passing additional attributes to this, I don't need to as I'm compiling on the front-end.
The alternative was to simply `fetch` the `.hbs` files from the client-side, parse, compile, add data, execute the template and inject the html, however, I didn't want to do the ajax calls. I wanted them to be inline on the initial request.

**Comment by nknapp** [comment]
Closing, because the issue seems to to contain solutions to the problem.
