### ISSUE TITLE
Saucelabs testing old Firefox (v45)

### ISSUE THREAD

**Issue by miketaylr** [wycats/handlebars.js#1524]
Unsure if it's intentional or not, but I just noticed that tests are run on Firefox 45 -- that's currently 21 versions old. Are there any technical reasons it's not running release versions?

**Comment by nknapp** [comment]
No, there is no reason for that. The configuration is in the Gruntfile. There is no version specified. I would expect SauceLabs to use the newest one...

I think it is important to let the tests run in older browsers. But it is most important in IE and Safari (which sadly doesn't work at all at the moment) and it should be *in addition to* the new browser versions and not *instead of*.

I you can find out what's going on, please let me know.
