### ISSUE TITLE
How to use external css files into hbs?

### ISSUE THREAD

**Issue by leomarques3** [wycats/handlebars.js#1539]
Hi guys, Im trying to make handlebars use external css files, but i don't know how to do. I searched a lot in the internet, but a lot of people said to use app.use(express.static(path.join(__dirname, '/public')); to add the static files. But this didn't work for me with handlebars, I guess it only work with express-handlebars, but I want to use handlebars only.

Is there another way to add css and images into the hbs?

**Comment by nknapp** [comment]
Handlebars itself is just a template to convert template+json into HTML or other types of text.

**Comment by nknapp** [comment]
Handlebars itself is just a library to convert template+json into HTML or other types of text.
Integrating CSS does not have anything to do with Handlebars.

However, using `app.use(express.statis)...` seems to be a good way to go if you are using `express`.

Without looking at your exact code, I cannot say what you are doing wrong.

> but I want to use handlebars only.

Do you want to embed your Handlebars-template into your HTML-templates using a `<script>`-tag, and then compile the template in the browser? If so, I'd like to discourage you from doing that in production. 

If you want to run Handlebars on the server, `express-handlebars` or `express-hbs` should provide a solid express-middleware for doing that (although I don't have much experience with any of those packages).

If you want to run your templates in the browser, in a single-page app or progressive-webapp, there are better alternatives than using Handlebars (Ember, if you like the Handlebars syntax, otherwise  React, Vue.js, Angular or Ractive.js).
