### ISSUE TITLE
Partial parameters are being applied to nested partials

### ISSUE THREAD

**Issue by migmuni** [wycats/handlebars.js#1550]
Hello,

I'm using Handlebars to prototype front-end at my workplace. I have multiple instances of partials with the `className` parameter, which adds classes beyond the default in my partial. Something I've run into, though, is where nested partials without a defined `className` will default to the `className` of the parent partial. Is this supposed to be the case?

Template:
```hbs
{{#> 'container' className='red'}}
  {{> 'content'}}
{{/container}}
```

Output:
```hbs
<div class="container red">
  <p class="red">Content</p>
</div>
```

Expected:
```hbs
<div class="container red">
  <p>Content</p>
</div>
```

A workaround is to always define `className`, even if I want it to be empty. So something like: `className=''`. This might not be ideal for me though as sometimes I'll use conditional statements to test whether a parameter is defined, then show different HTML depending on the value.

Here's a JS Fiddle I managed to create showing the issue, expected output, and the workaround:
https://jsfiddle.net/t0mkgn24/6/

**Comment by nknapp** [comment]
When you call `{{#> container className='red'}}, the `className` is added to the current context. When you call `{{> content}}` the context does not change, so `className` is still there.

I can see that it's painful for you, but I think this would not be a trivial change.

* The simplest option would be to discard the `this` context in a partial and only take the hash as a context. But this is a major change in behavior `{{> partial newContext}}` would not work anymore.
* Partials could be to be compiled differently to receive two contexts. One is passed along when calling other partials. The other one isn't and contains just the parameters. This would require changes in the compiler. 

In both cases changes would be breaking and would require either a feature flag or a major version bump. 

I have written this down in such detail, because this may become relevant some time. But currently I would say: You'll just have to use the workaround.

**Comment by nknapp** [comment]
@migmuni There is a runtime-option "explicitPartialContext" (see https://handlebars-draft.knappi.org/guide/api-reference.html) that seems to do what you need. I haven't seen it myself and I haven't tested it, but the description looks like what you need.

**Comment by andreyvolokitin** [comment]
Is it possible to get a reference to the local context? If we have clashing name from some parent context, we could just reference a local context specifically inside a partial: `localCtx.clashingVar`. If it's not possible, how difficult is to implement this? Empty dumb context as the first partial argument just to "erase" parent context seems like littering in the code... An introduced flag is also seems not ideal, because sometimes you want to use parent by default (actually I relied on this until I encountered this issue). So, essentially it seems like it is best to allow choosing a context to use — parent by default, and local with some keyword reference.

**Comment by migmuni** [comment]
I forgot about this issue, but I thought I'd mention eventually I found passing a custom context like so `{{> @partial-block context}}` was a better solution than the alternative I had in my initial comment and still allowed me to inherit parameters when needed. I think this is what you're talking about @andreyvolokitin.

https://handlebarsjs.com/guide/partials.html#partial-contexts
https://jsfiddle.net/wf5n2Lko/1/

**Comment by andreyvolokitin** [comment]
I didn't yet wrap my head around this, but `@partial-block` seems like a thing too use in "parent-child" scenario. But often you just use a component deep in your markup only to find out that i.e. a global data variable is clashing with it. So there's no `@partial-block`, and if it would be required to add something like this, then just passing a dumb empty context to affected component might be a considerably more "ligthweight" "solution"

What I talking about was just being able to reference local context (with no parent values included, but just directly passed parameters), like `@local.parameter` instead of `parameter`.  So it wouldn't require including any non-obvious things in a code, but just getting a context you need explicitly
