### ISSUE TITLE
Import of `handlebars/runtime` throws error in TypeScript

### ISSUE THREAD

**Issue by MickL** [wycats/handlebars.js#1610]
When importing `handlebars/runtime` TypeScript throws multiple errors:

<img width="1078" alt="Bildschirmfoto 2019-11-21 um 12 31 54" src="https://user-images.githubusercontent.com/5103210/69334585-5e304380-0c5b-11ea-9e62-bf26449bc62d.png">

Handlebars version: 4.5.3
Typescript: 3.5.3

I am NOT using the `@types/handlebars` module.

When setting `"noImplicitAny": true` within tsconfig.json it throws no error but still shows the same message as a warning.

**Comment by nknapp** [comment]
Could you try to verify if this also happens with older TypeScript versions? It would be helpful to know if a change in typescript does this, because actually this issue came up once #1499 and should have been solved.

**Comment by papasmile** [comment]
Hi, tried on TypeScript 2.x and had that same error BUT I think the problem is that `runtime.d.ts` is not packaged:  https://github.com/wycats/handlebars.js/blob/fd3ca85d136d9f7f11faeda2fbcb3fd56f05cf42/package.json#L105-L115

Manually downloading `runtime.d.ts` into `node_modules\handlebars` resolved that error for me.  Easy to fix by just adding that item to `"files"`, I think.

**Comment by nknapp** [comment]
published in 4.7.3
