### ISSUE TITLE
Error: Template was precompiled with a newer version of Handlebars than the current runtime.

### ISSUE THREAD

**Issue by andreasrosdal** [wycats/handlebars.js#1622]
Freeciv-web uses Handlebars to implement part of the user-interface. However, recently Handlebars has stopped working on the Vagrant and Docker installs, with the following error message:

Error: Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0)

This bug has been reported here onthe Freeciv-web Github repo: https://github.com/freeciv/freeciv-web/issues/293

This is how Handlebars is installed in the Vagrant container server:
https://github.com/freeciv/freeciv-web/blob/develop/scripts/install/deb.sh#L111

This is how Handlebars templates are precompiled:
https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/pom.xml#L284

This is the bundled Handlebars runtime:
https://github.com/freeciv/freeciv-web/blob/develop/freeciv-web/src/main/webapp/javascript/libs/handlebars.runtime-v4.0.11.js

Even updating the Handlebars file to 4.3.0 doesn't seem to solve this.

Any help with resolving this problem is appreciated! Thanks!

Freeciv-web - https://github.com/freeciv/freeciv-web/ 
https://www.freecivweb.org/

**Comment by nknapp** [comment]
Looks loke you have updated the Compiler but not the runtime...

Updating the runtime in webapp directory should help. Could you try that again? Or is there another handlebars.runtimenhidden somewhere

The other way is to use "npm install handlebars@4.2" in the deb.sh file, but I wouldn't recommend that.

Personally, I would update the build process, so that the runtime in taken from the extracted npm package. Or use webpack to build and optimize the ui, but that's probably beyond the scope your question.

**Comment by nknapp** [comment]
@andreasrosdal It seems like you have resolved this issue, correct?

**Comment by andreasrosdal** [comment]
@nknapp Yes

**Comment by nknapp** [comment]
thanks, I'll close this now.
