### ISSUE TITLE
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.

### ISSUE THREAD

**Issue by ramesh2611** [wycats/handlebars.js#1646]
I'm running my test case in locally with following versions
@angular-devkit/architect    0.803.23
@angular-devkit/core         8.3.23
@angular-devkit/schematics   8.3.23
@schematics/angular          8.3.23
@schematics/update           0.803.23
rxjs                         6.4.0
Node: 12.14.1

handlers with the 4.5.3 versions i was getting my repost
![coverage with old version](https://user-images.githubusercontent.com/59706009/73068813-27341380-3ed2-11ea-904a-f0ca0a3b904d.PNG)
 
and recently i have verified my components and i have done npm install after this i have run the coverage then is was throwing error like: 

               Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "branches" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "lines" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details

and report was generating but it looks like:
![latest verison](https://user-images.githubusercontent.com/59706009/73069009-a1649800-3ed2-11ea-8169-b17ae9ffdb06.PNG)
 and the latest version is 4.7.2

@wycats 
@ kpdecker

**Comment by nknapp** [comment]
See #1636 pleas a

**Comment by nknapp** [comment]
The basic answer is that istanbul-reports and many others are using Handlebars with custom classes as input. Which was not intended, documented or tested, but it still worked. Up to 4.5.3.

It was changed in 4.6.0 due to recurring security problems. Now prototype access is forbidden by default and opt-in via runtime options.

In your case, I believe you should ask the angular-people to bump to the a newer version of istanbul-reports, nyc or something in that direction. It had already been fixed.

**Comment by nknapp** [comment]
I have experienced this issue today as well. If upgrading you dependencies (I think `jest-scripts` or something like that) try deleting and recreating your `yarn.lock`-file. That solved our problem today.

**Comment by probfacile** [comment]
just try `npm update istanbul-reports --depth 3` to check if it solve the issue for you.

**Comment by sketchy-ota** [comment]
> just try `npm update istanbul-reports --depth 3` to check if it solve the issue for you.

I liked this approach, but it didn't resolve my problem.  After tracing the root package, I updated it and the errors went away:
`npm list`
searched for the instanbul-reports module then traced the root and updated:

`npm install karma-coverage-istanbul-reporter@latest`

**Comment by ashwingattani** [comment]
@sketchy-ota where did you install the karma-coverage-istanbul-reporter? inside istanbul-reports module?

**Comment by sketchy-ota** [comment]
@ashwingattani, after calling `npm list` in the terminal, I ran a word search in the terminal for `instanbul-reports` then traced the root module that depended on it, which in my case was the `karma-coverage-istanbul-reporter` (could be different for others possibly?).

So instead of trying to update just the dependency, I updated the whole library with '**@latest**', hence:
`npm install karma-coverage-instanbul-reporter@latest`

**Comment by ashwingattani** [comment]
@sketchy-ota, thanks for the update. for me, npm deep clean and `npm update istanbul-reports --depth 3` worked in the end 🖖🏽

**Comment by sudip-mukherjee** [comment]
@sketchy-ota you saved my day buddy. this is working fine ( m using Linux 16.4)
