### ISSUE TITLE
Alternative delimiters or changing delimiters

### ISSUE THREAD

**Issue by sebpiq** [wycats/handlebars.js#227]
Hi !

I couldn't find if there is the possibility to change the delimiters for blocks or variables (`{{}}`, `{{#`, ...).
From a quick look in the source, the delimiters seem hard-coded in a regular expression, but I'd like to have the confirmation of that !?
Without giving complete freedom to chose the delimiters, it would be cool to be able to choose between alternative syntax.

My current problem is that I am using Django, and the delimiters of Django's templating langage and handlebar's clash. Therefore, where I need to use both template langages, I have to use very clumsy syntax like :

``` javascript
{% raw %}
    <img src="{{#if user.mugshot_url}}{{user.mugshot_url}}{{else}}{% endraw %}{{ USER_DEFAULT_PIC_URL }}{% raw %}{{/if}}"/>
{% endraw %}
```

Thanks !

**Comment by erquhart** [comment]
@wagenet so it's been two years and Handlebars is still the top templating tool for js. Is there willingness to even consider overcoming the limitations to making the delimiter configurable? I'm using Handlebars as a part of a library for static site generation, and precompiling doesn't apply if you're generating a static Angular app. It doesn't make sense to require users of the generator lib to use alternate tags throughout their entire Angular application for the sake of the templating language, when we know the templating will generally be quite minimal.

I'm aware (and appreciative!) of @jonschlinkert's solution, but this really is a core concern.

Thoughts?

**Comment by korya** [comment]
I am not sure about their plans. I believe the main argument against doing it remains the same: this requires changing the parser, which is generated and tested during build time.

Our case was similar to yours one. We use handlebars to assemble our HTML templates during the project compilation (build time), and we use angular at runtime.

First we started to escape the angular templates; that is in HTML file you write `<span>\{{name}}</span>` instead of just `<span>{{name}}</span>`. This approach did not work well since you had to remember always to escape these expressions; and even worse if you forgot to do it you got some weird errors messages during the build.

Since most of our effort is spent writing the angular apps, we decided to change the delimiters of handlebars rather than angular ones. We tried to reconfigure handlebars to use different delimiters at run-time. But we failed to integrate it into our setup. We use assemble.io to build the HTML templates, and there was always an edge case that did not work for us. Hence at some point we just decided to fork Handlebars and change its delimiters in the lexer itself.

We decided to change the delimiters to `<{{` and `}}>` (from the default `{{` and `}}`). The fork can be found at https://github.com/PlanitarInc/handlebars.js. The main change is in the lexer definition https://github.com/wycats/handlebars.js/compare/master...PlanitarInc:master#diff-a13581e6dfc1c61c90703da188230cbc, other changes are just fixes for the tests. 

I hope this can help you.

**Comment by erquhart** [comment]
Yeah, there's that route.

Here's the thing: Jon wrote a succinct script that just wraps handlebars and, unless there are caveats that I'm not aware of, it works. I'm hoping that the maintainers are at least open to this approach for now - simply allow users to specify alternate tags once, globally.
