### ISSUE TITLE
Can I use multiple helpers in a single tag?

### ISSUE THREAD

**Issue by fuqcool** [wycats/handlebars.js#304]
like `{{ helper1 helper2 text }}`, you know sometimes only one helper is not enough to do the work.

**Comment by cssguru** [comment]
@Znarkus Using your method, when I pass in two helpers that have safe strings applied my code breaks.  The first time I pass data through it comes in as a string, but the second filter the value being passed appears to be an object?  In my debugger it shows as 'n a line break and then string:'my value';  Not sure what SafeString does to the value, but passing it through it twice doesn't seem to work out to well.

        Handlebars.registerHelper('shortNumber', function (value) {
            //return new Handlebars.SafeString(iSpot.number.shortNumber(value)); // Breaks
            return iSpot.number.shortNumber(value);  // Works
        });
        Handlebars.registerHelper('asDollars', function (value) {
            //return new Handlebars.SafeString(iSpot.number.asDollars(value)); // Breaks
            return iSpot.number.asDollars(value); // Works
        });

**Comment by breandr** [comment]
+1 @amwmedia approach - `{{pluralize (titleize (humanize schema.name))}}`

**Comment by GriffinSauce** [comment]
+1 that looks like a nice clean syntax.

**Comment by arbiz** [comment]
+1 @amwmedia Works perfectly thanks

**Comment by zunc** [comment]
@amwmedia thanks you much, that so well

**Comment by ixisio** [comment]
@breandr approach works like a charme, but just w/o `Handlebars.SafeString()` as @cssagogo mentioned above.

So you can do smth. like:

```
{{> partial text=(concat value (default extension 'PDF')) }}
```

**Comment by cunjieliu** [comment]
thanks

**Comment by MWolman1990** [comment]
I ran into this issue myself. I know I'm really late on this, but I have a solution that worked for me. Please forgive me if this was already mentioned (I didn't take the time to check). This is not the coolest solution and it is technically not a direct answer to your question but it is a solution to the problem (running multiple functions on one value).

I keep all of my helper functions in a separate file. Because they are all in the same place, I can pass the value to one helper and then just call whatever other functions I have in my helper function's file. So:

`{{ function1 value }}`

*helper file*
```
function2 (value) {
   // code
}

function1 (value) {
   // code
   function2(value)
   // code
   return value;
}
```

Of course, this is a simple way of being able to use as many functions as you want. You could even designate a base function that acts as your "chainer".

`{{ chainer value }}`

*helper file*
```
function1 (value) {
   // code
}
function2 (value) {
   // code
}
function3 (value) {
   // code
}
function4 (value) {
   // code
}

function chainer(value) {
   function1(value)
   function2(value)
   function3(value)
   function4(value)
   return value;
}
```
I haven't done this myself but I don't see why it wouldn't work. 

**Note** You only have to register the functions that you want to use in your html as handlebars helpers. I personally have all of mine registered because I use them independently of each other, but you don't have to if you don't foresee yourself needing to use it directly.

A throwback to procedural programming :)
