### ISSUE TITLE
Chrome extension manifest v2 restricts use of eval

### ISSUE THREAD

**Issue by asgraf** [wycats/handlebars.js#453]
Handlebars will not work in Chrome extensions with manifest_version: 2 because of a new security policy that restricts the use of eval and eval-like syntax.

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
 handlebars.js:1402
JavaScriptCompiler.createFunctionContext handlebars.js:1402
JavaScriptCompiler.compile handlebars.js:1320
compile handlebars.js:2105
(anonymous function) handlebars.js:2112
(anonymous function) panel.js:14 <--- my script called Handlebars.compile()

**Comment by rsrsps** [comment]
That basically defeats the whole point of using a CSP to prevent injection.

**Comment by BigBlueHat** [comment]
FWIW, Cloudant (based on Apache CouchDB) recently changed their in-database script processing to also prevent `eval()` and `new Function()` https://console.bluemix.net/docs/services/Cloudant/release_info/deprecations.html#disabled-javascript-constructors

Precompiling templates into JS works for some scenarios, but not for all of them. It'd be great if there were other options, so that Handlebars.js could be used more places.

But...that might just be wishful thinking. :smiley: 💭

**Comment by noahgibbs** [comment]
> Is it not possible to follow the CSP guide here?
> 
> "You can allow it by adding 'unsafe-eval' to your sources list"

At this point, it looks like Chrome extension V3 isn't allowing you to add unsafe-eval to your sources list.
