### ISSUE TITLE
Anchor tag confuses rendering of template

### ISSUE THREAD

**Issue by eotope** [wycats/handlebars.js#497]
Hi,

I experienced the following issue with 1.0.0-rc-3

I have a partial which is nested in another partial.
When I am using {{{htmlText}}} (a SafeString) in the deeply nested partial and I have the string '&lt;a&gt;link&lt;/a&gt;' in it, errors in the DOM hierarchy of both partials are occuring. The rendered HTML is wrong.

When I am removing just this link - it works. It works also with other HTML tags except &lt;a&gt;&lt;/a&gt;.

**Comment by DarthDerrr** [comment]
I have the same issue as manikrathee described - please fix this! The original resolution the asker used was a workaround - I'm working with a requirement that needs nested a tags.

**Comment by ericsoco** [comment]
@manikrathee, @DarthDerrr, this is not a Handlebars issue, it's actually per HTML5 spec.

As you can see in [this fiddle](http://jsfiddle.net/ericsoco/7Lmjukdp/),

```html
<a href="https://flickr.com">
    <div>
        Foo!
        <a href="https://github.com">Bar!</a>
    </div>
</a>
```

Renders out to:
```html
<div><a href="https://flickr.com">
        Foo!
        </a><a href="https://github.com">Bar!</a>
    </div>
```

**Comment by manikrathee** [comment]
@ericsoco I'm not sure that's correct. AFAIK, in HTML5, it is valid to wrap anchors around block-level elements. See also: http://html5doctor.com/block-level-links-in-html-5/

**Comment by ericsoco** [comment]
@manikrathee You're right. Looks like the problem I'm seeing is with nested anchor tags; your example does not have this in the markup, so is a separate issue.

**Comment by FarhadG** [comment]
I'm curious if we have a resolution for this... I'm running into the same issue.

**Comment by stevenvachon** [comment]
Try it in a browser -- what does it render? I wouldn't think that Handlebars should affect this at all because it builds strings and not a DOM.

**Comment by FarhadG** [comment]
When I wrap a collection of elements around the anchor tag, the anchor tag doesn't `encapsulate` the children, as the HTML tree suggests.

For example:

```html
{{foreach data}}
  <a href="#">
     <aside>...</aside>
  </a>
{{/foreach}}
```

... renders:

```html
<a href="#"></a>
<article>...</article>
```

**Comment by nknapp** [comment]
Have you had a look at the HTML source-code. Because what you see in the dev-tools is mostly the interpretation of the browser. Btw, there is not `foreach`-builtin-helper in the Handlebars core. It should read `{{#each}}...{/each}` with a `#`

**Comment by FarhadG** [comment]
Yes, the source code is what I had included above. My apologies, the `forEach` method is a helper within the `Ghost` library. Pretty much the same functionality. I really have no idea how to get the nested children to be wrapped by an `<a>`

**Comment by ErisDS** [comment]
Hey @FarhadG what happens if you take the handlebars helpers away and code the same thing in plain HTML? I think you'll find the same thing happens, and it's due to invalid HTML nothing to do with handlebars.

**Comment by FarhadG** [comment]
Without that, it actually does what I expect for it to do. My intention is basically have an entire block of elements be able to be hyperlinked. If there's a better way or workaround, I'm open to suggesstions.

Source:
<img width="356" alt="screen shot 2016-07-28 at 8 58 06 am" src="https://cloud.githubusercontent.com/assets/1647596/17219824/a9f70f9e-54a1-11e6-9990-a8d0f0975680.png">

HTML:
<img width="261" alt="screen shot 2016-07-28 at 8 58 24 am" src="https://cloud.githubusercontent.com/assets/1647596/17219831/b115dbf2-54a1-11e6-8dc1-fbc9d7b60990.png">

**Comment by stevenvachon** [comment]
```js
console.log( require("handlebars").compile("{{#each posts}}<a href=\"#\"><article class=\"grid item\"><div class=\"post-inside\"><h1>hello</h1></div></article></a>{{/each}}")({posts:[0]}) )'
```
produces:
```html
<a href="#"><article class="grid item"><div class="post-inside"><h1>hello</h1></div></article></a>
```

I think this is a Ghost problem.

**Comment by manikrathee** [comment]
If you view my comment from earlier, that was done within middleman and produced the same issue.




On Thu, Jul 28, 2016 at 1:11 PM -0700, "Steven Vachon" <notifications@github.com> wrote:










console.log( require("handlebars").compile("{{#each posts}}<a href=\"#\"><article class=\"grid item\"><div class=\"post-inside\"><h1>hello</h1></div></article></a>{{/each}}")({posts:[0]}) )'



produces:

<a href="#"><article class="grid item"><div class="post-inside"><h1>hello</h1></div></article></a>



I think this is a Ghost problem.

**Comment by stevenvachon** [comment]
@manikrathee 
```js
console.log( require("handlebars").compile("{{#each posts}}<a href=\"#\" title=\"Wrapper\"><ul><li>Something</li></ul></a>{{/each}}")({posts:[0]}) )
```
produces:
```html
<a href="#" title="Wrapper"><ul><li>Something</li></ul></a>
```

**Comment by manikrathee** [comment]
I understand. I'm calling out that this isn't isolated to Ghost.





On Fri, Jul 29, 2016 at 9:07 AM -0700, "Steven Vachon" <notifications@github.com> wrote:












@manikrathee 

console.log( require("handlebars").compile("{{#each posts}}<a href=\"#\" title=\"Wrapper\"><ul><li>Something</li></ul></a>{{/each}}")({posts:[0]}) )



produces:

<a href="#" title="Wrapper"><ul><li>Something</li></ul></a>

**Comment by stevenvachon** [comment]
It has not be reproduced in this thread.

**Comment by ErisDS** [comment]
If there's a reproducible difference between handlebars's `{{#each}}` and Ghost's `{{#foreach}}` that's a Ghost bug and should be raised on https://github.com/TryGhost/Ghost. I have not been able to find one whilst testing out the cases shown in this thread.

So far as I can tell, every reported issue in this thread is due to creating illegal HTML structures by nesting handlebars helpers which create interactive content.

HTML5 does not allow interactive content inside of an <a> tag ([see this stackoverflow](http://stackoverflow.com/questions/9882916/are-you-allowed-to-nest-a-link-inside-of-a-link)).

It doesn't matter if you use `{{#each}}` or `{{#foreach}}`, if you view source you will see the HTML structure that you expect (even if it is illegal) but if you use chrome to inspect elements on the page you will see the browser changes where it renders the end of the `</a>` in order to create a valid HTML structure.

Case in point is the [fiddle linked in the first response](http://jsfiddle.net/ericsoco/7Lmjukdp/) on this thread. View the frame source and you will see:

![](https://puu.sh/qohl1.png)

But if you inspect using chrome, you will see: 

![](https://puu.sh/qohmR.png)

To demonstrate further, see [this fiddle I created](https://jsfiddle.net/9D88g/52/)

The first example has no handlebars and is essentially the same as the previous fiddle. The browser will not render this HTML as desired because of the nested <a> tags.

The next two examples show an each loop in handlebars, looping over some content. In the first example, the content being output is plain text & the browser renders it as desired. In the second example we use triple-braces to render HTML which contains an <a> tag, making the HTML structure invalid and so the browser will compensate.

Here's what the chrome inspector shows:

![](https://puu.sh/qohvL.png).

Fundamentally, you cannot nest `<a>` tags. Specifically to Ghost, if you want to loop over posts and wrap the content in an `<a>` tag you cannot nest the `{{content}}` helper within the loop. The `{{excerpt}}` helper will provide an HTML-free version of the content which can be looped over and nested within an `<a>` tag.

If there are further questions around how to theme Ghost, I highly recommend visiting the #themes channel on [Ghost's slack](https://ghost.org/slack) rather than posting in this thread.

**Comment by davision** [comment]
As of today, this is still a painful issue here. Is there any solution or workaround for this? Wrong rendering occurs whenever <a> is wrapping other elements.
