### ISSUE TITLE
Including a <script> tag in a template?

### ISSUE THREAD

**Issue by julien51** [wycats/handlebars.js#531]
We're trying to include a couple gists in our content, but obviously adding `<script src="https://gist.github.com/4332573.js"/></script>` in a handlebar template breaks it.

Is there a way to "escape" the script tags?

**Comment by santafebound** [comment]
I could definitely use help here! http://stackoverflow.com/questions/35122587/injecting-javascript-files-into-handlebars-js?noredirect=1#comment57965873_35122587

There are some libraries that aren't executable from "within" the template. I have a pop up script that works just fine so long as the link is hit from outside a template, but that defeats the entire purpose for me. I'm iterating through a collection of blog items and I need each blog image to generate a popup. Either way, the problem is not being able to include a script inside the template. Assumed this would be a fairly obvious and commonly used feature of a Handlebars template...

**Comment by santafebound** [comment]
Can't you just escape the scripts like this?

<script src="jquery.min.js"><{{!}}/script>
<script src="view.min.js?auto"><{{!}}/script>

**Comment by letsrock85** [comment]
santafebound You are Genious!

**Comment by nknapp** [comment]
@letsrock85 may I recommend, that you precompile your templates? You avoid such problems altogehter and get a better performance.

**Comment by nevercast** [comment]
@nknapp Just to clarify, precompiling templates does not fix this. The script tag *is* embedded in the DOM, but it is *not* executed.

**Comment by nknapp** [comment]
@nevercast Handlebars just computes the string that contains the script.

What you do with the string is up to you. You can insert it into the DOM, but that does not execute the scripts. That is correct.

For solutions, see https://stackoverflow.com/questions/4619668/executing-script-inside-div-retrieved-by-ajax

**Comment by nevercast** [comment]
Thanks @nknapp, I ended up defining my own script type. `<script type="text/x-after-hashchange">` and invoking those after handlebars had done its work. Which I believe is similar to the solutions you linked.
