### ISSUE TITLE
node.js handlebars

### ISSUE THREAD

**Issue by DominicBoettger** [wycats/handlebars.js#804]
I i set a variable in a helper under nodejs the variable is the same on the next request. Even if i create a new instance with handlebars.create.

I think it has something todo with handlebars.runtime, but have no idea how to solve that problem. I think it's not very useful to mess around in the global scope.

**Comment by Sebastian-Fitzner** [comment]
Hi, 

for me it seems like the bug is existing. The comment above is just a workaround. 

When I use `.create()` I expect a new handlebars instance is created which can be used next to another handlebars instance without interfering each other. But that is happening. 

What is the purpose of `.create()`?
