### ISSUE TITLE
Please Re-Open Issue #250 (index plus one)

### ISSUE THREAD

**Issue by machineghost** [wycats/handlebars.js#828]
Issue #250 was closed, but there is still no solution for the very basic problem of wanting to do:

```
 1. foo
 2. bar
 3. baz
```

with Handlebars out of the box.  All you can do now is:

```
{{each fakeList}}
{{@index}}. {{this}}<br/>
{{/each}}
```

which results in:

```
 0. foo
 1. bar
 2. baz
```

Since templates are designed to produce human-readable HTML, it makes no sense that the only way to count in Handlebars is with a computer-focused zero-based index, and one should not need a custom plug-in for such an extremely basic use case.  Please re-consider re-opening the referenced ticket.

**Comment by just-boris** [comment]
Since the original issue is locked, I have to post it here.

As I got from the original thread, you have a solution with `math`. I don't think that is a good solition, my templates is pretty clear, I don't have any other purposes for `math` in my templates rather than for one-based index.

I can write `increment` helper as well, but it will do it on every call, howewer you can assign this counter once at start of each iteration.

Also I don't get why do you allow to have `first` and `last` variables but not `index_1`. What is the difference? As you can see from the #250, it is such a common use-case.

**Comment by kpdecker** [comment]
Locking this issue too, citing my original comment.

Regarding `first` and `last`, these were implemented prior to subexpressions and now can't be changed (that and `last` needs be aware of length to properly work). I ran performance tests and each additional data field adds a fairly significant overhead and there are common enough use cases that don't need this that we aren't going to penalize them when users can opt in.

If using a subexpression to increment is painful enough for you, then you can always write your own version of `each`.
